spring.application.name=reservego-router
# ===============================
# SERVER CONFIG
# ===============================

server.port=8097
#security.require-ssl=false
#server.ssl.key-store-password=innobliss123$
#server.ssl.key-store=classpath:keystore.jks
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=direkt12.devourin.com
logging.level.org.hibernate.SQL=DEBUG


# ===============================
# MYSQL DB CONFIG
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/reservego-router?storage_engine=InnoDB&autoReconnect=true&useSSL=false&&characterEncoding=utf8&useUnicode=true&createDatabaseIfNotExist=true


spring.datasource.username=root

spring.datasource.password=innobliss123$

#spring.datasource.password=dev$park
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# LOGGING
# ===============================

reservego.baseurl=https://stagingapi.reservego.co